export const PERMISSIONS = {
  consultation_create: ['handler', 'sub_admin', 'super_admin'],
  consultation_view_own: ['handler', 'sub_admin', 'super_admin'],
  consultation_view_all: ['sub_admin', 'super_admin', 'payn_staff'],
  consultation_status_change: ['sub_admin', 'super_admin', 'payn_staff'],
  consultation_memo_payn: ['super_admin', 'payn_staff'],
  consultation_memo_payn_view: ['sub_admin'],
  hardware_view: ['sub_admin', 'super_admin', 'geotech_staff'],
  hardware_view_only: ['payn_staff'],
  hardware_status_change: ['sub_admin', 'super_admin', 'geotech_staff'],
  hardware_memo: ['super_admin', 'geotech_staff'],
  hardware_memo_view: ['sub_admin'],
  revenue_view: ['sub_admin', 'super_admin', 'payn_staff'],
  attachment_view: ['sub_admin', 'super_admin', 'payn_staff', 'geotech_staff'],
  excel_all: ['sub_admin', 'super_admin', 'payn_staff'],
  excel_hardware: ['sub_admin', 'super_admin', 'geotech_staff'],
  live_dashboard: ['handler', 'sub_admin', 'super_admin', 'payn_staff', 'geotech_staff'],
  handler_map: ['handler', 'sub_admin', 'super_admin'],
  store_map: ['handler', 'sub_admin', 'super_admin', 'payn_staff', 'geotech_staff'],
  ranking: ['handler', 'sub_admin', 'super_admin', 'payn_staff', 'geotech_staff'],
  statistics_full: ['sub_admin', 'super_admin', 'payn_staff'],
  statistics_view: ['handler'],
  statistics_hardware_only: ['geotech_staff'],
  qna: ['handler', 'sub_admin', 'super_admin'],
  payn_tips: ['handler', 'sub_admin', 'super_admin'],
  success_stories: ['handler', 'sub_admin', 'super_admin'],
  success_stories_view: ['payn_staff', 'geotech_staff'],
  resources: ['handler', 'sub_admin', 'super_admin'],
  resources_view: ['payn_staff', 'geotech_staff'],
  notice_view: ['handler', 'sub_admin', 'super_admin', 'payn_staff', 'geotech_staff'],
  notice_create: ['sub_admin', 'super_admin'],
  user_management: ['sub_admin', 'super_admin'],
  level_change: ['super_admin'],
  permission_settings: ['super_admin'],
  team_management: ['sub_admin', 'super_admin'],
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
